kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-physter
subjects:
- kind: ServiceAccount
  name: operator-physter
  namespace: default
roleRef:
  kind: ClusterRole
  name: operator-physter
  apiGroup: rbac.authorization.k8s.io
